import { createContext, useContext, useState, useEffect, ReactNode } from "react";

type Language = "pt" | "en";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pt: {
    "nav.manifesto": "Quem Somos",
    "nav.approach": "Nossa Atuação",
    "nav.clients": "Clientes",
    "nav.engage": "Falar com a Lidtek",
    "hero.tag": "Para empresas com tecnologia. Sem direção.",
    "hero.title1": "Sua empresa já tem ",
    "hero.title1_italic": "tecnologia.",
    "hero.title2": "Mas ela tem direção?",
    "hero.desc": "Somos a equipe de tecnologia que sua empresa deveria ter. Fornecemos profissionais de tecnologia e desenvolvemos ferramentas e soluções sob medida para o seu negócio.",
    "hero.explore": "Entender o diagnóstico",
    "problem.tag": "O diagnóstico",
    "problem.title": "Tecnologia sem direção vira ",
    "problem.title_italic": "obstáculo.",
    "problem.title_end": " Não importa o quanto você já investiu nela.",
    "problem.desc": "A Lidtek é uma empresa de tecnologia que ajuda outras empresas a vender mais, otimizar processos, reduzir custos e melhorar experiência do cliente, tudo através de tecnologia. Fornecemos profissionais capacitados terceirizando desenvolvimento e desenvolvendo ferramentas e projetos personalizados sob medidas como sistemas, plataformas, softwares e aplicativos.",
    "problem.debt.title": "O problema invisível",
    "problem.debt.desc": "Quando a tecnologia não foi pensada para crescer com o negócio, cada novo processo vira uma gambiarra. O problema não aparece — até aparecer de vez.",
    "problem.generic.title": "A consequência",
    "problem.generic.desc": "A tecnologia passa a consumir energia da operação, em vez de impulsionar resultados.",
    "problem.scale.title": "O que empresas maduras fazem diferente",
    "problem.scale.desc": "Param de terceirizar a responsabilidade por projeto e passam a ter alguém que responde pela tecnologia de ponta a ponta.",
    "problem.solution.title": "O modelo Lidtek",
    "problem.solution.desc": "Substituímos improviso por estrutura. Assumimos sua tecnologia como departamento, não como projeto.",
    "manifesto.tag": "O que nos move",
    "manifesto.main": "A maioria das empresas de tecnologia entrega um projeto e some.",
    "manifesto.main_bold": "Nós não vendemos projeto. Assumimos a área.",
    "manifesto.desc": "Se você consegue descrever o seu problema, nós conseguimos desenvolver uma solução!",
    "manifesto.precision.title": "Estrutura antes de código",
    "manifesto.precision.desc": "Antes de propor qualquer solução, entendemos como sua operação funciona hoje. Não chegamos com resposta pronta para uma pergunta que ainda não fizemos.",
    "manifesto.silent.title": "Tecnologia que não aparece",
    "manifesto.silent.desc": "A melhor tecnologia é aquela que simplesmente funciona. Sem ruído. Sem surpresa. Sem dependência.",
    "manifesto.active.title": "Responsabilidade contínua",
    "manifesto.active.desc": "Não entregamos e desaparecemos. Assumimos a evolução da sua operação como compromisso permanente.",
    "manifesto.section_quote": "A Lidtek é a equipe de tecnologia que sua empresa deveria ter.",
    "approach.tag": "Como entregamos",
    "approach.title": "Construído para a sua operação de hoje — e para o que ela vai exigir amanhã.",
    "approach.desc": "Não vendemos projetos isolados. Construímos a base que sustenta sua operação — e permanecemos responsáveis por ela enquanto o negócio cresce.",
    "approach.code.title": "Código que cresce com o negócio, não contra ele",
    "approach.code.desc": "Desenvolvemos com clareza, organização e visão de continuidade. Nada é feito apenas para funcionar hoje.",
    "approach.data.title": "Dados que chegam quando você precisa decidir",
    "approach.data.desc": "Organizamos sistemas e dados para que sua operação tenha visibilidade e controle.",
    "approach.security.title": "Sua operação não pode depender de soluções frágeis",
    "approach.security.desc": "Construímos para durar e proteger o que é vital. Tecnologia deve ser porto seguro, não fonte de risco.",
    "approach.perf.title": "Eficiência que respeita o seu tempo",
    "approach.what.title": "Nossa Atuação",
    "approach.what.item1.title": "Alocação de profissionais de TI.",
    "approach.what.item1.desc": "Fornecemos equipe de desenvolvimento para atuar dentro do negócio da sua empresa.",
    "approach.what.item2.title": "Projetos personalizados e sob medida.",
    "approach.what.item2.desc": "Desenvolvemos soluções customizadas para a sua empresa (Sistemas, Apps, Automações, Softwares).",
    "approach.who.title": "A Lidtek é para quem?",
    "approach.who.item1": "Empresa que quer sair de sistemas engessados para soluções mais modernas",
    "approach.who.item2": "Empresa que precisa de uma ferramenta sob medida",
    "approach.who.item3": "Empresa que quer melhorar processos e automatizar ferramentas",
    "approach.who.item4": "Empresa que precisa de uma equipe eficiente de tecnologia",
    "approach.who.item5": "Empresa que não quer montar e gerir equipe e estrutura de TI sozinha",
    "model.tag": "Caminho planejado",
    "model.method": "Nosso método",
    "model.subtitle": "A Lidtek desenha o processo com você, levanta as necessidades e constrói ferramentas digitais sob medida para sua empresa.",
    "model.step1.title": "Entendimento Real",
    "model.step1.desc": "Entramos na sua operação antes de propor qualquer solução.",
    "model.step2.title": "Direção Definida",
    "model.step2.desc": "Arquitetura e prioridades claras antes de executar.",
    "model.step3.title": "Execução Focada",
    "model.step3.desc": "Cada entrega documentada, testada e revisada com você. Nada entra em produção no escuro.",
    "model.step4.title": "Ajuste Contínuo",
    "model.step4.desc": "Acompanhamos o crescimento e ajustamos a rota.",
    "model.step5.title": "Liderança Ativa",
    "model.step5.desc": "Assumimos responsabilidade real pela sua tecnologia.",
    "cta.tag": "Próximo passo",
    "cta.title": "Se você chegou até aqui, provavelmente já sabe que algo precisa mudar na sua operação tecnológica.",
    "cta.desc": "Nós podemos ser o departamento de tecnologia e inovação da sua empresa. A Lidtek fornece a equipe e faz a gestão para sua empresa.",
    "cta.btn": "Falar com a Lidtek",
    "cta.footer": "Estrutura para empresas que cresceram além do que a tecnologia atual consegue sustentar.",
    "operations.tag": "Governança & Estrutura",
    "operations.title": "Você sabe o que está acontecendo. Sem depender de alguém te explicar.",
    "operations.desc": "Não entregamos apenas tecnologia. Entregamos visibilidade sobre o que está funcionando, o que precisa mudar e o que vem a seguir.",
    "operations.ind1.title": "Você define a direção. Nós garantimos que o caminho está sendo percorrido.",
    "operations.ind1.value": "Controle",
    "operations.ind2.title": "Nada acontece por impulso. Cada decisão tem contexto e tem próximo passo.",
    "operations.ind2.value": "Processo",
    "operations.ind3.title": "Indicadores simples e objetivos para saber onde estamos e para onde vamos.",
    "operations.ind3.value": "Clareza",
    "operations.ind4.title": "Documentação organizada e decisões registradas. Nada depende da memória de alguém.",
    "operations.ind4.value": "Auditoria",
    "ideal.tag": "Perfil de parceria",
    "ideal.title1": "Para empresas que já cresceram.",
    "ideal.title2": "E que perceberam que a tecnologia não cresceu na mesma velocidade.",
    "ideal.desc": "Não somos uma fábrica de software comum. Atuamos como departamento para empresas que levam tecnologia a sério.",
    "ideal.pro.tag": "Sinergia",
    "ideal.pro.title": "É para você se:",
    "ideal.pro.item1": "Sua operação cresceu, mas a tecnologia ficou para trás — seja um sistema legado, um processo manual ou ferramentas que não se comunicam",
    "ideal.pro.item2": "Quer previsibilidade em vez de improviso",
    "ideal.pro.item3": "Enxerga tecnologia como base estratégica, não apenas suporte",
    "ideal.pro.item4": "Valoriza clareza, organização e responsabilidade contínua",
    "ideal.con.tag": "Desalinhamento",
    "ideal.con.title": "Talvez não seja o momento se:",
    "ideal.con.item1": "Busca apenas um orçamento pontual",
    "ideal.con.item2": "Quer apenas executar uma ideia isolada",
    "ideal.con.item3": "Trata tecnologia como custo, não como investimento",
    "ideal.con.item4": "Prefere decisões rápidas sem estrutura",
    "ideal.con.footer": "Preferimos ser transparentes agora do que entregar menos do que o seu negócio realmente precisa.",
    "footer.rights": "Estrutura para empresas que crescem.",
    "footer.menu": "Menu",
    "footer.social": "Social",
    "footer.privacy": "Política de Privacidade",
    "footer.terms": "Termos de Serviço",
    "footer.desc": "Atuamos como departamento de tecnologia para empresas em crescimento. Estrutura, direção e responsabilidade contínua.",
    "history.tag": "Nossa Origem",
    "history.title": "A Lidtek não começou do zero.",
    "history.desc": "Nascemos da fusão da Lution — especialista em desenvolvimento de sistemas — com a RLB Sistemas, com experiência em automação de processos e operações.",
    "history.footer": "Dois históricos. Uma estrutura. Um compromisso: tecnologia que sustenta quem está crescendo.",
    "testimonials.tag": "Clientes",
    "testimonials.title": "Voz de quem confia na nossa estrutura",
    "testimonials.quote1.text": "A Lidtek não nos entregou apenas um software, mas sim um braço de tecnologia que entende o nosso negócio. Eles assumiram a responsabilidade que antes era pulverizada e hoje temos clareza total da nossa operação.",
    "testimonials.quote1.author": "Nome do Cliente",
    "testimonials.quote1.role": "Diretor de Operações"
  },
  en: {
    "nav.manifesto": "Who We Are",
    "nav.approach": "Our Operation",
    "nav.clients": "Clients",
    "nav.engage": "Talk to Lidtek",
    "hero.tag": "For companies with technology. Without direction.",
    "hero.title1": "Your company already has ",
    "hero.title1_italic": "technology.",
    "hero.title2": "But does it have direction?",
    "hero.desc": "Technology without direction is a cost. With structure, it's a competitive advantage.",
    "hero.explore": "Understand the diagnosis",
    "problem.tag": "The Diagnosis",
    "problem.title": "Technology without direction becomes an ",
    "problem.title_italic": "obstacle.",
    "problem.title_end": " No matter how much you've already invested in it.",
    "problem.desc": "There's a point where technology stops being a solution and becomes a maintenance cost. The operation grows, decisions become more complex, and systems — whether they are spreadsheets, software, or manual processes — start to slow down what should be accelerating.",
    "problem.debt.title": "The Hidden Problem",
    "problem.debt.desc": "When technology wasn't designed to grow with the business, every new process becomes a workaround. The problem doesn't show up — until it shows up all at once.",
    "problem.generic.title": "The Consequence",
    "problem.generic.desc": "Technology starts to drain operational energy instead of driving results.",
    "problem.scale.title": "What Mature Companies Do Differently",
    "problem.scale.desc": "They stop outsourcing responsibility per project and start having someone who answers for the technology from end to end.",
    "problem.solution.title": "The Lidtek Model",
    "problem.solution.desc": "We replace improvisation with structure. We take over your technology as a department, not a project.",
    "manifesto.tag": "What drives us",
    "manifesto.main": "Most technology companies deliver a project and vanish.",
    "manifesto.main_bold": "We don’t sell projects. We take over the area.",
    "manifesto.desc": "Technology isn't an isolated project. It's an area that requires direction, accountability, and continuity.",
    "manifesto.precision.title": "Structure Before Code",
    "manifesto.precision.desc": "Before proposing any solution, we understand how your operation works today. We don't arrive with a ready answer to a question we haven't asked yet.",
    "manifesto.silent.title": "Invisible Technology",
    "manifesto.silent.desc": "The best technology is the one that just works. No noise. No surprises. No dependency.",
    "manifesto.active.title": "Continuous Accountability",
    "manifesto.active.desc": "We don’t just deliver and disappear. We assume the evolution of your operation as a permanent commitment.",
    "manifesto.section_quote": "Technology is not a project. It's the area that decides if the rest of the business will be able to scale.",
    "approach.tag": "How We Deliver",
    "approach.title": "Built for your operation today — and for what it will demand tomorrow.",
    "approach.desc": "We don't sell isolated projects. We build the foundation that sustains your operation — and remain responsible for it as the business grows.",
    "approach.code.title": "Code that grows with the business, not against it",
    "approach.code.desc": "We develop with clarity, organization, and a vision of continuity. Nothing is built just to work for today.",
    "approach.data.title": "Data that arrives when you need to decide",
    "approach.data.desc": "We organize systems and data so your operation has visibility and control.",
    "approach.security.title": "Your operation cannot depend on fragile solutions",
    "approach.security.desc": "We build to last and protect what is vital. Technology should be a safe harbor, not a source of risk.",
    "approach.perf.title": "Efficiency that respects your time",
    "approach.what.title": "Our Operation",
    "approach.what.item1.title": "IT Professional Allocation.",
    "approach.what.item1.desc": "We provide a development team to work within your company's business.",
    "approach.what.item2.title": "Custom and Tailored Projects.",
    "approach.what.item2.desc": "We develop customized solutions for your company (Systems, Apps, Automations, Software).",
    "approach.who.title": "Who is Lidtek for?",
    "approach.who.item1": "Companies looking to move away from rigid systems toward more modern solutions",
    "approach.who.item2": "Companies that need a custom-built tool",
    "approach.who.item3": "Companies that want to improve processes and automate tools",
    "approach.who.item4": "Companies that need an efficient technology team",
    "approach.who.item5": "Companies that don't want to build and manage an IT team and structure on their own",
    "model.tag": "Planned Path",
    "model.method": "Our Method",
    "model.subtitle": "Technology requires structure. And someone who answers for it.",
    "model.step1.title": "Real Understanding",
    "model.step1.desc": "We dive into your operation before proposing any solution.",
    "model.step2.title": "Defined Direction",
    "model.step2.desc": "Clear architecture and priorities before execution.",
    "model.step3.title": "Focused Execution",
    "model.step3.desc": "Each delivery documented, tested, and reviewed with you. Nothing goes into production in the dark.",
    "model.step4.title": "Continuous Adjustment",
    "model.step4.desc": "We monitor growth and adjust the path accordingly.",
    "model.step5.title": "Active Leadership",
    "model.step5.desc": "We take real responsibility for your technology.",
    "cta.tag": "Next step",
    "cta.title": "If you've made it this far, you probably already know that something needs to change in your technological operation.",
    "cta.desc": "The conversation doesn't start with a proposal. It starts with understanding. You talk about your operation. We talk about what would make sense. No pitch. No ready-made solution.",
    "cta.btn": "Talk to Lidtek",
    "cta.footer": "Structure for companies that have grown beyond what the current technology can sustain.",
    "operations.tag": "Governance & Structure",
    "operations.title": "You know what's happening. Without depending on someone to explain it to you.",
    "operations.desc": "We don’t just deliver technology. We deliver visibility into what's working, what needs to change, and what comes next.",
    "operations.ind1.title": "You define the direction. We guarantee the path is being followed.",
    "operations.ind1.value": "Control",
    "operations.ind2.title": "Nothing happens on impulse. Every decision has context and a next step.",
    "operations.ind2.value": "Process",
    "operations.ind3.title": "Simple and objective indicators to know where we are and where we're going.",
    "operations.ind3.value": "Clarity",
    "operations.ind4.title": "Organized documentation and recorded decisions. Nothing depends on someone's memory.",
    "operations.ind4.value": "Audit",
    "ideal.tag": "Partnership Profile",
    "ideal.title1": "For companies that have already grown.",
    "ideal.title2": "And realized that technology hasn't grown at the same speed.",
    "ideal.desc": "We are not a standard software factory. We act as a department for companies that take technology seriously.",
    "ideal.pro.tag": "Synergy",
    "ideal.pro.title": "We're a fit if:",
    "ideal.pro.item1": "Your operation has grown, but technology has fallen behind — whether it's a legacy system, a manual process, or tools that don't communicate",
    "ideal.pro.item2": "You want predictability instead of improvisation",
    "ideal.pro.item3": "You see technology as a strategic foundation, not just support",
    "ideal.pro.item4": "You value clarity, organization, and continuous accountability",
    "ideal.con.tag": "Mismatch",
    "ideal.con.title": "It might not be the right time if:",
    "ideal.con.item1": "You're looking for just a one-off quote",
    "ideal.con.item2": "You just want to execute an isolated idea",
    "ideal.con.item3": "You treat technology as a cost, not an investment",
    "ideal.con.item4": "You prefer quick decisions without structure",
    "ideal.con.footer": "We prefer to be transparent now rather than deliver less than your business truly needs.",
    "footer.rights": "Structure for companies that grow.",
    "footer.menu": "Menu",
    "footer.social": "Social",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.desc": "We act as a technology department for growing companies. Structure, direction, and continuous accountability.",
    "history.tag": "Our Genesis",
    "history.title": "Lidtek didn't start from scratch.",
    "history.desc": "We were born from the merger of Lution — specialized in systems development — and RLB Sistemas, with expertise in process and operations automation.",
    "history.footer": "Two histories. One structure. One commitment: technology that sustains those who are growing.",
    "testimonials.tag": "Testimonials",
    "testimonials.title": "Voices of those who trust our structure",
    "testimonials.quote1.text": "Lidtek didn't just deliver software, but a technology arm that understands our business. They took over the responsibility that was previously scattered, and today we have complete clarity of our operation.",
    "testimonials.quote1.author": "Client Name",
    "testimonials.quote1.role": "Operations Director"
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("pt");

  useEffect(() => {
    const browserLang = navigator.language.split("-")[0];
    const isPortuguese = browserLang === "pt";
    setLanguage(isPortuguese ? "pt" : "en");
  }, []);

  const t = (key: string) => {
    return (translations[language] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
